spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/unionfly
      username: unionfly
      password: unionfly

server:
  security:
    permitUrl: /api/user/auth/login,/api/user/auth/register
    permitAuthUrl: /api/user/auth/**
  jwt:
    expiration: 18000
    prefix: "Bearer "